name: spectrumdevice-docs-pages

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[doc]
    - name: Create doc pages and commit to docs branch
      run: |
        git config --local user.name "crnbaker"
        git config --local user.email "christian.baker@kcl.ac.uk"
        git fetch
        git status
        git checkout docs
        git status
        git rebase --onto main
        pdoc --docformat google -o ./docs spectrumdevice
        git add .
        git commit -m 'Automatic documentation update'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: docs

